dist: trusty
language: node_js
node_js:
- "9"
- "8"
- "6"

jobs:
  include:
    - stage: test
      script: npm run build && npm test
    - stage: release
      if: branch = master
      node_js: "8"
      script: npm run build && ./scripts/authenticate.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
