dist: trusty
language: node_js
node_js:
- "9"
- "8"
- "6"

jobs:
  include:
    - stage: test
      before_script: npm run build
      script: npm test
    - stage: release
      if: branch = master
      node_js: "8"
      before_script: npm run build
      script: ./scripts/authenticate.sh
      after_script: echo "Git and NPM are authenticated."
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
