dist: trusty
sudo: true
language: node_js
node_js:
  - "9"
  - "8"
  - "6"
before_script: npm run build
script: npm test

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: "8"
      script: sh ./scripts/authenticate.sh
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run release
