parameters:
  node_version: ''

steps:
- task: NodeTool@0
  inputs:
    versionSpec: ${{ parameters.node_version }}
  displayName: 'Install Node.js'

- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build'
